"""
A hand-curated knowledge base of business archetypes.

This grounds the deterministic ("demo mode") agent pipeline in realistic,
varied data instead of random numbers, so the product is meaningfully
useful even with zero external API keys. When AI is enabled, the LLM's
output is used instead/on top of this data.

min_budget_pkr is a realistic ABSOLUTE floor for doing this properly --
deliberately NOT a fraction of whatever budget the user typed. Costs that
only ever scale as a percentage of the input can never rule anything out,
which is what let every profile see the same categories regardless of
budget. This floor is what real filtering is based on.

None of these figures are guarantees of profitability -- they are rough,
illustrative planning estimates only.
"""

BUSINESS_ARCHETYPES = [
    {
        "key": "home_organization",
        "title": "Home Organization Products",
        "description": "Curated storage, labeling and closet-organization kits sold direct-to-consumer.",
        "tags": ["retail", "product", "home", "diy", "design"],
        "base_cost": 0.18,  # fraction of budget, used for the cost breakdown once affordable
        "min_budget_pkr": 15000,
        "demand": "high",
        "competition": "medium",
        "difficulty": "easy",
        "margin_range": (35, 55),
        "channels": ["online_store", "marketplace", "social_media"],
    },
    {
        "key": "customized_gifts",
        "title": "Customized Gift Business",
        "description": "Personalized gifts (engraving, printing, hampers) for birthdays, weddings and corporate clients.",
        "tags": ["retail", "creative", "gifts", "events", "design"],
        "base_cost": 0.15,
        "min_budget_pkr": 10000,
        "demand": "high",
        "competition": "high",
        "difficulty": "easy",
        "margin_range": (40, 60),
        "channels": ["social_media", "marketplace", "online_store"],
    },
    {
        "key": "digital_products",
        "title": "Digital Products & Templates",
        "description": "Templates, e-books, presets or notion systems sold as one-time digital downloads.",
        "tags": ["digital", "creative", "writing", "design", "low_capital"],
        "base_cost": 0.05,
        "min_budget_pkr": 3000,
        "demand": "medium",
        "competition": "high",
        "difficulty": "medium",
        "margin_range": (70, 90),
        "channels": ["online_store", "social_media"],
    },
    {
        "key": "social_media_management",
        "title": "Social Media Management Agency",
        "description": "Manage content, posting and ads for local small businesses on a monthly retainer.",
        "tags": ["services", "marketing", "digital", "b2b", "low_capital"],
        "base_cost": 0.08,
        "min_budget_pkr": 5000,
        "demand": "high",
        "competition": "high",
        "difficulty": "medium",
        "margin_range": (50, 75),
        "channels": ["b2b", "social_media"],
    },
    {
        "key": "local_food_delivery",
        "title": "Local Home-Kitchen Food Delivery",
        "description": "Home-cooked meals, tiffin service or a niche snack line delivered locally.",
        "tags": ["food", "retail", "local", "service"],
        "base_cost": 0.30,
        "min_budget_pkr": 20000,
        "demand": "high",
        "competition": "high",
        "difficulty": "medium",
        "margin_range": (20, 35),
        "channels": ["marketplace", "social_media", "physical_store"],
    },
    {
        "key": "print_on_demand",
        "title": "Print-on-Demand Apparel & Merch",
        "description": "Custom-designed apparel and merchandise produced only after each sale, no inventory risk.",
        "tags": ["retail", "design", "digital", "low_capital"],
        "base_cost": 0.06,
        "min_budget_pkr": 5000,
        "demand": "medium",
        "competition": "high",
        "difficulty": "easy",
        "margin_range": (20, 40),
        "channels": ["online_store", "marketplace", "social_media"],
    },
    {
        "key": "mobile_accessories",
        "title": "Mobile Accessories Retail",
        "description": "Cases, chargers and gadgets sourced wholesale and resold online or from a small stall.",
        "tags": ["retail", "tech", "product"],
        "base_cost": 0.25,
        "min_budget_pkr": 30000,
        "demand": "medium",
        "competition": "high",
        "difficulty": "easy",
        "margin_range": (25, 45),
        "channels": ["marketplace", "physical_store", "online_store"],
    },
    {
        "key": "educational_services",
        "title": "Educational Services / Tutoring",
        "description": "Subject tutoring, test-prep or skill workshops delivered online or in person.",
        "tags": ["services", "education", "low_capital", "teaching"],
        "base_cost": 0.05,
        "min_budget_pkr": 3000,
        "demand": "high",
        "competition": "medium",
        "difficulty": "medium",
        "margin_range": (55, 80),
        "channels": ["services", "social_media", "b2b"],
    },
    {
        "key": "handmade_crafts",
        "title": "Handmade Crafts & Decor",
        "description": "Artisanal candles, pottery or decor items sold through markets and online shops.",
        "tags": ["retail", "creative", "design", "diy"],
        "base_cost": 0.15,
        "min_budget_pkr": 12000,
        "demand": "medium",
        "competition": "medium",
        "difficulty": "easy",
        "margin_range": (40, 60),
        "channels": ["marketplace", "social_media", "physical_store"],
    },
    {
        "key": "freelance_tech_services",
        "title": "Freelance Tech / Dev Services",
        "description": "Websites, apps or automation tools built for small businesses on a project basis.",
        "tags": ["services", "tech", "digital", "b2b", "low_capital"],
        "base_cost": 0.04,
        "min_budget_pkr": 3000,
        "demand": "high",
        "competition": "medium",
        "difficulty": "hard",
        "margin_range": (60, 85),
        "channels": ["b2b", "services"],
    },
    {
        "key": "tailoring_boutique",
        "title": "Tailoring & Custom Clothing",
        "description": "Custom stitching, alterations or a small ready-to-wear line for local and online customers.",
        "tags": ["retail", "creative", "fashion", "design", "local"],
        "base_cost": 0.20,
        "min_budget_pkr": 18000,
        "demand": "high",
        "competition": "medium",
        "difficulty": "medium",
        "margin_range": (35, 55),
        "channels": ["physical_store", "social_media", "marketplace"],
    },
    {
        "key": "event_planning",
        "title": "Event & Wedding Planning Services",
        "description": "Coordinate small events, weddings or corporate functions -- vendors, decor and logistics.",
        "tags": ["services", "events", "creative", "local"],
        "base_cost": 0.10,
        "min_budget_pkr": 8000,
        "demand": "high",
        "competition": "medium",
        "difficulty": "medium",
        "margin_range": (30, 50),
        "channels": ["social_media", "services", "b2b"],
    },
    {
        "key": "vehicle_detailing",
        "title": "Car & Bike Detailing Services",
        "description": "Mobile or fixed-location washing, polishing and interior detailing for vehicle owners.",
        "tags": ["services", "local", "tech"],
        "base_cost": 0.22,
        "min_budget_pkr": 25000,
        "demand": "medium",
        "competition": "medium",
        "difficulty": "medium",
        "margin_range": (35, 55),
        "channels": ["physical_store", "social_media", "services"],
    },
    {
        "key": "fitness_coaching",
        "title": "Fitness & Wellness Coaching",
        "description": "Personal training, home workout plans or small group fitness sessions.",
        "tags": ["services", "health", "teaching", "low_capital"],
        "base_cost": 0.06,
        "min_budget_pkr": 4000,
        "demand": "high",
        "competition": "medium",
        "difficulty": "medium",
        "margin_range": (55, 75),
        "channels": ["services", "social_media", "b2b"],
    },
    {
        "key": "import_export_reselling",
        "title": "Import/Wholesale Reselling",
        "description": "Bulk-source products (local or imported) and resell at retail scale across multiple channels.",
        "tags": ["retail", "product", "tech", "scale"],
        "base_cost": 0.35,
        "min_budget_pkr": 60000,
        "demand": "medium",
        "competition": "high",
        "difficulty": "hard",
        "margin_range": (20, 40),
        "channels": ["marketplace", "online_store", "b2b"],
    },
]

DEMAND_SCORE = {"low": 45, "medium": 70, "high": 92}
COMPETITION_SCORE = {"low": 90, "medium": 65, "high": 40}  # lower competition scores higher
DIFFICULTY_SCORE = {"easy": 90, "medium": 65, "hard": 40}
